
- hosts: dsnet
  remote_user: mau
  become: yes
  become_method: sudo
  gather_facts: yes
  vars:
    repo_name: "{{ lookup('env', 'CIRCLE_PROJECT_REPONAME') }}" # master.v0.12
    VMIP: ansible_host
  tasks:

    - debug: var=ansible_host

    - file: # make /opt/app dir
        path: "/opt/favel8s/repos/{{ repo_name }}"
        state: directory
        mode: 0755

    - name: Copy playbook
      copy:
          src: playbooks
          dest: "/opt/favel8s/repos/{{ repo_name }}/"

    - name: Copy playbook
      copy:
          src: inventory
          dest: "/opt/favel8s/repos/{{ repo_name }}/"        


    