version: 2.1

orbs:
  python: circleci/python@0.2.1

commands:
  python-test:
    steps:
      - run:
          command: pip install pylint
      - python/save-cache
      - run:
          command: | 
            pylint -d=R,W,C jobs/
          
#             
#             python -m jobs.jobs.restore_prod_dumps
#           name: Python-Tests
      


jobs:
  build-test:
    working_directory: ~/app
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: pip install pylint
      - run:
          command: pylint -d=R,W,C jobs/

#   deploy-job:
#     working_directory: /opt/app
#     executor: python/default    
#     steps:    
#       - checkout
#       - python/load-cache
#       - python/install-deps
#       - run:
#           command: |
#             echo DEPLOYINGGGGGG
#             # scp -r dbmanagers/* username@my-server:/opt/dbmanagers


workflows:
  build-test:
    jobs:
      - build-test
#       - deploy-job:
#         requires:
#           - build-and-test # Only deploy once the build job has completed
#         filters:
#           branches:
#             only: master # Only deploy on the master branch        
