version: 2.1

orbs:
  python: circleci/python@0.2.1
  gcp-gcr: circleci/gcp-gcr@0.7.1
      

jobs:
  build-test:
    working_directory: ~/app
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - run:
          command: sudo apt-get install pylint
      - python/save-cache
      - run:
          command: pylint -d=R,W,C jobs/
 

  deploy:
    working_directory: ~/app
    executor: gcp-gcr/default    
    steps:    
      - checkout
      # build and push Docker image
      - run: |
          echo $GCLOUD_SERVICE_KEY > /tmp/gcloud-service-key.json
          cat /tmp/gcloud-service-key.json
      - gcp-gcr/build-image:
          image: superpython
          registry-url: asia.gcr.io
          dockerfile: Dockerfile
          tag: latest
      - gcp-gcr/gcr-auth
      - gcp-gcr/push-image:
          image: superpython
          registry-url: asia.gcr.io
          tag: latest
          digest-path: /tmp/digest.txt
      - run: |
          echo "Digest is: $(</tmp/digest.txt)"

          
      - run: |
          scp -o StrictHostKeyChecking=no -r ../app mau@34.85.75.223:~/app

# echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
# docker push CircleCI-Public/circleci-demo-docker:$TAG


workflows:
  build-test:
    jobs:
      #- build-test
      - deploy:
          requires:
            - build-test # Only deploy once the build job has completed
          filters:
            branches:
              only: master # Only deploy on the master branch        
