

- hosts: dsnet
  remote_user: mau
  become: yes
  become_method: sudo
  gather_facts: yes
  vars:
    APPDIR: "/opt/app"
    VMIP: ansible_host
    service_account_file: /home/mau/credentials/data-science-273411-066f734ce5bb.json
    project: data-science-273411  
  tasks:

    - debug: var=ansible_host

    - file: # make /opt/app dir
        path: "{{ APPDIR }}"
        state: directory
        mode: 0755   

    - name: gcloud auth activate-service-account
      shell: "gcloud auth activate-service-account data-science-obl@{{ project }}.iam.gserviceaccount.com --key-file={{ service_account_file }}"
      
    - name: gcloud auth configure-docker
      shell: gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://asia.gcr.io

    